// USER REDUCER
export const USER_LOADED = 'USER_LOADED';
export const USER_ERROR = 'USER_ERROR';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const FOLLOW_USER = 'FOLLOW_USER';
export const GET_FOLLOWING = 'GET_FOLLOWING';
export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const FOLLOWING_ERROR = 'FOLLOWING_ERROR';

// TOAST REDUCER
export const POPUP_TOAST = 'POPUP_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

// AUTH REDUCER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

// TWIT REDUCER
export const GET_ALL_TWITS = 'GET_ALL_TWITS';
export const GET_USER_TWITS = 'GET_USER_TWITS';
export const GET_FOLLOWING_TWITS = 'GET_FOLLOWING_TWITS';
export const POST_TWIT = 'POST_TWIT';
export const DELETE_TWIT = 'DELETE_TWIT';
export const TWITS_ERROR = 'TWITS_ERROR';

// PROFILE REDUCER
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

// MODAL REDUCER
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const SET_LOADING = 'SET_LOADING';
